name: Git Pull on EC2 via SSM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger git pull on EC2 via SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Git Pull React App" \
            --instance-ids "${{ secrets.AWS_INSTANCE_ID }}" \
            --region "${{ secrets.AWS_REGION }}" \
            --parameters commands='
              cd /datadisk/react/add-fruit-react &&
              git pull
            ' \
            --output text