name: Git Pull and Deploy React App via SSM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Turn on EC2
        run: |
          aws ec2 start-instances --instance-ids i-07ea54875f1e02de6
          echo "Waiting for instance to be turned on"
          aws ec2 wait instance-running --instance-ids i-07ea54875f1e02de6

      - name: Wait for SSM to become available
        run: |
          echo "Waiting for EC2 instance $INSTANCE_ID to register with SSM..."

          for i in {1..30}; do
            echo "Checking instance status (Attempt $i)..."

            aws ssm describe-instance-information \
              --region "$AWS_REGION" \
              --output json \
              > ssm_status.json

            cat ssm_status.json

            STATUS=$(jq -r ".InstanceInformationList[] | select(.InstanceId==\"$INSTANCE_ID\") | .PingStatus" ssm_status.json)

            if [ "$STATUS" = "Online" ]; then
              echo "✅ SSM PingStatus is Online!"
              break
            elif [ -z "$STATUS" ]; then
              echo "⏳ Instance not found in SSM list yet."
            else
              echo "🔁 SSM PingStatus is: $STATUS"
            fi

            sleep 10
          done

          if [ "$STATUS" != "Online" ]; then
            echo "❌ Instance never became Online in SSM."
            exit 1
          fi

      - name: Git Pull React App on EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          INSTANCE_ID: ${{ secrets.AWS_INSTANCE_ID }}
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Git Pull React App" \
            --instance-ids "$INSTANCE_ID" \
            --region "$AWS_REGION" \
            --parameters 'commands=[
              "sudo -u ssm-user bash -c \"\
                cd /home/ssm-user && \
                if [ ! -d 'add-fruit-react/.git' ]; then \
                  git clone https://github.com/ayonrakib/add-fruit-react.git; \
                else \
                  cd add-fruit-react && git checkout master && git pull origin master; \
                fi\""
            ]' \
            --output text

      - name: Build React App on EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          INSTANCE_ID: ${{ secrets.AWS_INSTANCE_ID }}
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Build React App" \
            --instance-ids "$INSTANCE_ID" \
            --region "$AWS_REGION" \
            --parameters 'commands=[
              "sudo -u ssm-user bash -c \"\
                source /home/ssm-user/.nvm/nvm.sh && \
                nvm use 17 && \
                cd /home/ssm-user/add-fruit-react && \
                npm install && npm run build\""
            ]' \
            --output text

      - name: Upload Build Folder to S3 from EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          INSTANCE_ID: ${{ secrets.AWS_INSTANCE_ID }}
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Upload Build to S3" \
            --instance-ids "$INSTANCE_ID" \
            --region "$AWS_REGION" \
            --parameters 'commands=[
              "sudo -u ssm-user bash -c \"\
                aws s3 cp /home/ssm-user/add-fruit-react/build/ s3://nodejs-bucket-ayon/ --recursive\""
            ]' \
            --output text

      - name: Stop EC2 Instance
        run: |
          aws ec2 stop-instances --instance-ids i-07ea54875f1e02de6
