name: Git Pull on EC2 via SSM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Trigger git pull on EC2 via SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_INSTANCE_ID }}
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo ${{ secrets.AWS_INSTANCE_ID }}
          echo ${{ secrets.AWS_REGION }}
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Git Pull React App" \
            --instance-ids "${{ secrets.AWS_INSTANCE_ID }}" \
            --region "${{ secrets.AWS_REGION }}" \
            --parameters commands='
              whoami && 
              cd /datadisk/react/add-fruit-react &&
              git status &&
              git show HEAD &&
              git checkout master &&
              git pull origin master
              git show HEAD &&
              cat pull.log
            ' \
            --output text